import type { Relic, RelicRarity } from "./types";

// 遗物稀有度权重（普通宝物节点）
export const RELIC_RARITY_WEIGHT: Record<RelicRarity, number> = {
  common: 45,
  rare: 30,    // 绿（普通/精英）
  epic: 18,    // 紫（精英/事件）
  legendary: 7, // 金（Boss/高级事件）
};

// 遗物池（按稀有度分组）
export const RELIC_POOL: Relic[] = [
  // ═══════════════════════════════════════════════════════
  // 一、贞观系列 — 武备与攻战（setId: "zhen Guan"）
  // ═══════════════════════════════════════════════════════
  {
    id: "liutao",
    name: "六韬",
    icon: "⚔️",
    rarity: "rare",
    setId: "zhenguan",
    category: "teamBuff",
    tags: ["attack", "team"],
    effect: { description: "全队攻击+10%", scope: "team" },
    effectText: "全队攻击+10%",
    effects: { physicalDamagePct: 0.10 },
    source: "treasure",
    lore: "太公吕望所著兵法，分为文韬、武韬、龙韬、虎韬、豹韬、犬韬六篇。太宗谓侍臣：'兵法之原，在于六韬。'",
  },
  {
    id: "sanlue",
    name: "三略",
    icon: "📜",
    rarity: "rare",
    setId: "zhenguan",
    category: "teamBuff",
    tags: ["attack", "team", "conditional"],
    effect: { description: "全队生命值>50%时，攻击额外+12%", scope: "team" },
    effectText: "全队生命值>50%时，攻击额外+12%",
    effects: { physicalDamagePct: 0.12 },
    source: "treasure",
    lore: "黄石公所传兵法，专述揽英雄、收人心之要诀。与《六韬》并称古代兵学双璧。",
  },
  {
    id: "liwei_gongwendui",
    name: "李卫公问对",
    icon: "🎓",
    rarity: "epic",
    setId: "zhenguan",
    category: "teamBuff",
    tags: ["followUp", "team"],
    effect: { description: "全队追击概率+18%，追击追加伤害+25%", scope: "team" },
    effectText: "全队追击概率+18%，追击追加伤害+25%",
    effects: { followUpChancePct: 0.18, followUpExtraDamagePct: 0.25 },
    source: "elite",
    lore: "李靖与唐太宗以问答形式穷尽奇正攻守之变，涵盖练兵、阵法、间谍等兵家要务，为唐代兵学最高成就。",
  },
  {
    id: "yinlingling",
    name: "阴陵令",
    icon: "🔮",
    rarity: "epic",
    setId: "zhenguan",
    category: "debuff",
    tags: ["enemy", "defenseDown"],
    effect: { description: "战斗开始，敌方全体防御-15%持续2回合", scope: "enemy" },
    effectText: "战斗开始，敌方全体防御-15%持续2回合",
    effects: { defensePct: -0.15 },
    source: "elite",
    lore: "陈婴佐刘邦起兵之遗策，述以弱胜强、以少敌众之法。太宗以此训诫天策府诸将，以为攻战之本。",
  },

  // ═══════════════════════════════════════════════════════
  // 二、开元系列 — 谋略与控制（setId: "kaiyuan"）
  // ═══════════════════════════════════════════════════════
  {
    id: "zhenguan_zhengyao",
    name: "贞观政要",
    icon: "📖",
    rarity: "rare",
    setId: "kaiyuan",
    category: "teamBuff",
    tags: ["strategy", "team"],
    effect: { description: "全队谋略+12%，敌方全体策防-8%全场", scope: "team" },
    effectText: "全队谋略+12%，敌方全体策防-8%全场",
    effects: { strategyPct: 0.12, strategyDamageReductionPct: -0.08 },
    source: "treasure",
    lore: "吴竞所撰，网罗太宗与魏征、房玄龄、杜如晦等人问答之语，记治国以民为本、兼听则明之心法。",
  },
  {
    id: "difan",
    name: "帝范",
    icon: "👑",
    rarity: "rare",
    setId: "kaiyuan",
    category: "teamBuff",
    tags: ["skill", "team", "speed"],
    effect: { description: "全队主动战法概率+12%，速度+6%", scope: "team" },
    effectText: "全队主动战法概率+12%，速度+6%",
    effects: { activeSkillChancePct: 0.12, speedPct: 0.06 },
    source: "treasure",
    lore: "太宗躬笔，亲述为君之道十二篇，以训诫太子。涵盖务农、阅武、崇文等治国大纲。",
  },
  {
    id: "chengui",
    name: "臣轨",
    icon: "🪶",
    rarity: "epic",
    setId: "kaiyuan",
    category: "debuff",
    tags: ["enemy", "strategyDown"],
    effect: { description: "每回合敌方随机2人谋略-10%持续2回合", scope: "enemy" },
    effectText: "每回合敌方随机2人谋略-10%持续2回合",
    effects: { strategyPct: -0.10 },
    source: "elite",
    lore: "武则天临朝时命百官习《臣轨》，以忠义约束群臣，述为臣修身、奉上、尽忠之道。",
  },
  {
    id: "xin_tangshu",
    name: "新唐书",
    icon: "📕",
    rarity: "epic",
    setId: "kaiyuan",
    category: "teamBuff",
    tags: ["strategy", "burn", "team"],
    effect: { description: "全队策略伤害附带灼烧：每回合损失目标最大兵力3%，持续2回合", scope: "team" },
    effectText: "全队策略伤害附带灼烧：每回合损失目标最大兵力3%，持续2回合",
    effects: { strategyDamagePct: 0.15, burnDamagePct: 0.03 },
    source: "elite",
    lore: "宋仁宗时欧阳修、宋祁奉诏重撰唐代兴亡之鉴，以理学笔法评述三百年治乱兴衰，寓史鉴于评断之中。",
  },

  // ═══════════════════════════════════════════════════════
  // 三、典谟系列 — 史学与文献（setId: "dianmo"）
  // ═══════════════════════════════════════════════════════
  {
    id: "jiu_tangshu",
    name: "旧唐书",
    icon: "🏛️",
    rarity: "rare",
    setId: "dianmo",
    category: "survival",
    tags: ["defense", "heal", "team"],
    effect: { description: "全队防御+12%，每回合全队恢复2%兵力", scope: "team" },
    effectText: "全队防御+12%，每回合全队恢复2%兵力",
    effects: { defensePct: 0.12, turnEndHealPct: 0.02 },
    source: "treasure",
    lore: "后晋刘昫等奉敕修，以唐代当朝史料为本，记本朝之史于本朝之人，详尽而真切，为唐史第一手资料。",
  },
  {
    id: "zizhi_tongjian",
    name: "资治通鉴",
    icon: "📗",
    rarity: "rare",
    setId: "dianmo",
    category: "teamBuff",
    tags: ["cleanse", "team"],
    effect: { description: "战斗开始时驱散全队各1个debuff", scope: "team" },
    effectText: "战斗开始时驱散全队各1个debuff",
    effects: {},
    source: "treasure",
    lore: "司马光承神宗之命，历十九年成《资治通鉴》，以编年体统合十七史，上起战国下及五代，以史为镜，以鉴来者。",
  },
  {
    id: "shitong",
    name: "史通",
    icon: "✒️",
    rarity: "epic",
    setId: "dianmo",
    category: "survival",
    tags: ["shield", "team"],
    effect: { description: "每场战斗首次我方有人受到致命伤害时，免疫此次伤害并获得25%最大兵力的护盾", scope: "team" },
    effectText: "每场战斗首次我方有人受到致命伤害时，免疫此次伤害并获得25%最大兵力的护盾",
    effects: { shieldPct: 0.25 },
    source: "elite",
    lore: "刘知几自著为中国第一部史学批评专著，批判前人修史之失，立史家独立之精神，才、学、识三者并重。",
  },
  {
    id: "yiwen_leiju",
    name: "艺文类聚",
    icon: "🌿",
    rarity: "epic",
    setId: "dianmo",
    category: "teamBuff",
    tags: ["speedDown", "defense", "team"],
    effect: { description: "敌方全体速度-12%，全队获得8%减伤", scope: "team" },
    effectText: "敌方全体速度-12%，全队获得8%减伤",
    effects: { speedPct: -0.12, physicalDamageReductionPct: 0.08, strategyDamageReductionPct: 0.08 },
    source: "elite",
    lore: "欧阳询等人奉敕编，汇先秦至隋代诗文典故于一炉，分门别类，以供文士采撷，是中国现存最早的类书之一。",
  },

  // ═══════════════════════════════════════════════════════
  // 四、武德系列 — 天下武功（setId: "wude"）
  // ═══════════════════════════════════════════════════════
  {
    id: "qinwang_pozhen",
    name: "秦王破阵乐",
    icon: "🎵",
    rarity: "rare",
    setId: "wude",
    category: "teamBuff",
    tags: ["doubleStrike", "attack", "team"],
    effect: { description: "全队连击概率+15%，攻击+8%", scope: "team" },
    effectText: "全队连击概率+15%，攻击+8%",
    effects: { cavalryDoubleStrikeChance: 0.15, physicalDamagePct: 0.08 },
    source: "treasure",
    lore: "李世民破刘武周时军中奏《破阵乐》，舞者百二十人，被甲执戟，以象战阵之容，气势磅礴，声震四方。",
  },
  {
    id: "taiji_quanpu",
    name: "太极拳谱",
    icon: "☯️",
    rarity: "rare",
    setId: "wude",
    category: "teamBuff",
    tags: ["speed", "firstStrike", "team"],
    effect: { description: "全队速度+15%，先手概率+15%", scope: "team" },
    effectText: "全队速度+15%，先手概率+15%",
    effects: { speedPct: 0.15, firstStrikeChancePct: 0.15 },
    source: "treasure",
    lore: "道家内修功法，讲究以柔克刚、四两拨千斤。后与少林武学相融，成为中国武学之最高哲理。",
  },
  {
    id: "shaolin_wuseng",
    name: "少林武僧记",
    icon: "🙏",
    rarity: "epic",
    setId: "wude",
    category: "teamBuff",
    tags: ["counter", "team"],
    effect: { description: "全队反击概率+25%，反击伤害+40%", scope: "team" },
    effectText: "全队反击概率+25%，反击伤害+40%",
    effects: { counterChancePct: 0.25, counterDamagePct: 0.40 },
    source: "elite",
    lore: "少林武僧助唐太宗平定王世充之乱后，李世民赐紫袈裟、田产。少林武学自此名震天下，以棍法、拳法著称于世。",
  },
  {
    id: "pei_clan_strat",
    name: "裴氏兵法",
    icon: "🎯",
    rarity: "epic",
    setId: "wude",
    category: "teamBuff",
    tags: ["followUp", "speed", "team"],
    effect: { description: "全队追击概率+20%，追击追加伤害额外+30%（基于速度差）", scope: "team" },
    effectText: "全队追击概率+20%，追击追加伤害额外+30%（基于速度差）",
    effects: { followUpChancePct: 0.20, followUpExtraDamagePct: 0.30 },
    source: "elite",
    lore: "裴仁基、裴行俨父子所创，以'以奇用兵'著称。裴氏三代为将，李密、王伯当皆出其门下。",
  },

  // ═══════════════════════════════════════════════════════
  // 五、散件遗物 — 全军增益（teamBuff）
  // ═══════════════════════════════════════════════════════
  {
    id: "hufu",
    name: "虎符",
    icon: "🐯",
    rarity: "common",
    setId: null,
    category: "teamBuff",
    tags: ["attack", "team"],
    effect: { description: "全队攻击+8%", scope: "team" },
    effectText: "全队攻击+8%",
    effects: { physicalDamagePct: 0.08 },
    source: "treasure",
    lore: "调兵信物，太尉与皇帝各执其一。大军将出，师出有名。",
  },
  {
    id: "chitu_horse",
    name: "赤兔马",
    icon: "🐎",
    rarity: "rare",
    setId: null,
    category: "teamBuff",
    tags: ["speed", "firstStrike", "team"],
    effect: { description: "全队速度+15%，先手概率+12%", scope: "team" },
    effectText: "全队速度+15%，先手概率+12%",
    effects: { speedPct: 0.15, firstStrikeChancePct: 0.12 },
    source: "treasure",
    lore: "吕布、关羽皆曾跨此名驹，日行千里。李元吉珍藏此马，以示荣耀。",
  },
  {
    id: "tianzi_sword",
    name: "天子剑",
    icon: "⚔️",
    rarity: "epic",
    setId: null,
    category: "teamBuff",
    tags: ["attack", "team"],
    effect: { description: "全队对HP>50%的目标伤害+25%", scope: "team" },
    effectText: "全队对HP>50%的目标伤害+25%",
    effects: { physicalDamagePct: 0.25 },
    source: "elite",
    lore: "李世民佩剑，玄武门之变中亲手斩杀建成、元吉。此后此剑藏于秦王府，传为天子之器。",
  },
  {
    id: "fenglin_huoshan",
    name: "风林火山",
    icon: "🔥",
    rarity: "epic",
    setId: null,
    category: "teamBuff",
    tags: ["firstStrike", "cleanse", "team"],
    effect: { description: "全队必定先手；每回合首次行动驱散自身1个debuff", scope: "team" },
    effectText: "全队必定先手；每回合首次行动驱散自身1个debuff",
    effects: { firstStrikeChancePct: 1.0 },
    source: "event",
    lore: "语出《孙子兵法》，李世民以此八字训玄甲军：'其疾如风，其徐如林，侵掠如火，不动如山。'",
  },

  // ═══════════════════════════════════════════════════════
  // 六、散件遗物 — 全队生存（survival）
  // ═══════════════════════════════════════════════════════
  {
    id: "shangyao",
    name: "伤药",
    icon: "💊",
    rarity: "common",
    setId: null,
    category: "survival",
    tags: ["heal", "team"],
    effect: { description: "战斗后全队恢复10%最大兵力", scope: "team" },
    effectText: "战斗后全队恢复10%最大兵力",
    effects: { turnEndHealPct: 0.10 },
    source: "treasure",
    lore: "民间行军散，以黄芪、当归炮制，军中随身携带，跌打损伤皆可用之。",
  },
  {
    id: "qinglong_dan",
    name: "青龙丹",
    icon: "🐉",
    rarity: "rare",
    setId: null,
    category: "survival",
    tags: ["heal", "team"],
    effect: { description: "每回合开始全队恢复3%兵力", scope: "team" },
    effectText: "每回合开始全队恢复3%兵力",
    effects: { turnEndHealPct: 0.03 },
    source: "treasure",
    lore: "药王孙思邈所制，以青龙为名，号称却病延年。实为军中常备跌打药膏配方。",
  },
  {
    id: "busiyao",
    name: "不死药",
    icon: "☠️",
    rarity: "legendary",
    setId: null,
    category: "survival",
    tags: ["lethalImmune", "heal", "team"],
    effect: { description: "免疫致命伤害后，全队获得2回合30%减伤和吸血", scope: "team" },
    effectText: "免疫致命伤害后，全队获得2回合30%减伤和吸血",
    effects: { lethalImmune: true, physicalDamageReductionPct: 0.30, strategyDamageReductionPct: 0.30 },
    source: "boss",
    lore: "秦始皇遣徐福求不死药未果，此为徐福弟子流落东瀛后辗转传回残方，后为李世民所得。",
  },
  {
    id: "budong_rushan",
    name: "不动如山",
    icon: "⛰️",
    rarity: "epic",
    setId: null,
    category: "survival",
    tags: ["shield", "team"],
    effect: { description: "战斗开始全队获得20%最大兵力的护盾", scope: "team" },
    effectText: "战斗开始全队获得20%最大兵力的护盾",
    effects: { shieldPct: 0.20 },
    source: "elite",
    lore: "张须陀剿匪时留下的军令要诀：'营盘如山，不可轻动。'以此为训全军结阵御敌。",
  },

  // ═══════════════════════════════════════════════════════
  // 七、散件遗物 — 全局减益（debuff）
  // ═══════════════════════════════════════════════════════
  {
    id: "xuanhua_fu",
    name: "宣花斧",
    icon: "🪓",
    rarity: "rare",
    setId: null,
    category: "debuff",
    tags: ["enemy", "defenseDown"],
    effect: { description: "全队普攻后使目标防御-8%持续2回合，可叠加3层", scope: "enemy" },
    effectText: "全队普攻后使目标防御-8%持续2回合，可叠加3层",
    effects: { defensePct: -0.08, debuffStacking: 3 },
    source: "treasure",
    lore: "隋末农民起义军广泛传用的战斧形制，以其威势震慑敌军胆气。",
  },
  {
    id: "xuan_dun",
    name: "玄盾",
    icon: "🛡️",
    rarity: "rare",
    setId: null,
    category: "debuff",
    tags: ["enemy", "counterUp"],
    effect: { description: "敌方全体受到反击伤害+25%", scope: "enemy" },
    effectText: "敌方全体受到反击伤害+25%",
    effects: {},
    source: "treasure",
    lore: "玄武岩锻制的重盾，乌黑如墨。尉迟敬德单鞭夺槊时凭此盾护驾，反震之力尤为惊人。",
  },
  {
    id: "yinyang_fan",
    name: "阴阳扇",
    icon: "🪭",
    rarity: "common",
    setId: null,
    category: "debuff",
    tags: ["enemy", "strategyDown"],
    effect: { description: "敌方全体策防-6%全场", scope: "enemy" },
    effectText: "敌方全体策防-6%全场",
    effects: { strategyDamageReductionPct: -0.06 },
    source: "treasure",
    lore: "谋士随身携带的折扇，扇骨以玄铁铸成。摇扇之间，计谋已定，敌军士气为之夺。",
  },
  {
    id: "qimen_dunjia",
    name: "奇门遁甲",
    icon: "☸️",
    rarity: "epic",
    setId: null,
    category: "debuff",
    tags: ["enemy", "strategyDown"],
    effect: { description: "每回合敌方随机2人谋略-10%持续2回合", scope: "enemy" },
    effectText: "每回合敌方随机2人谋略-10%持续2回合",
    effects: { strategyPct: -0.10 },
    source: "elite",
    lore: "道家秘传之术，以天干地支演布阵图。李靖平定辅公祏之乱时曾借此识破敌军阵法虚实。",
  },
  {
    id: "taiping_yaoshu",
    name: "太平要术",
    icon: "📿",
    rarity: "epic",
    setId: null,
    category: "debuff",
    tags: ["enemy", "cleanse"],
    effect: { description: "战斗开始驱散敌方全体1个增益", scope: "enemy" },
    effectText: "战斗开始驱散敌方全体1个增益",
    effects: {},
    source: "event",
    lore: "秦末黄巾道所藏秘典，张角得之而起三十六方。裴仁基剿匪时缴获残卷，上载以弱胜强之要诀。",
  },

  // ═══════════════════════════════════════════════════════
  // 八、散件遗物 — 资源获取（resource）
  // ═══════════════════════════════════════════════════════
  {
    id: "jubaopen",
    name: "聚宝盆",
    icon: "💰",
    rarity: "common",
    setId: null,
    category: "resource",
    tags: ["gold", "resource"],
    effect: { description: "金币+15%", scope: "global" },
    effectText: "金币+15%",
    effects: { resourceEfficiencyPct: 0.15 },
    source: "treasure",
    lore: "江南豪商沈万三传世的铜盆，号称万物投入皆可化为金银。实为唐代商帮记账的砝码容器。",
  },
  {
    id: "zizhong_che",
    name: "辎重车",
    icon: "🛒",
    rarity: "rare",
    setId: null,
    category: "resource",
    tags: ["recruit", "resource"],
    effect: { description: "每层额外获得1次征兵机会", scope: "global" },
    effectText: "每层额外获得1次征兵机会",
    effects: { extraRecruitTimes: 1 },
    source: "treasure",
    lore: "李渊晋阳起兵时车队绵延数里，粮草兵械一应俱全，为大军持久作战之根基。",
  },
  {
    id: "zhaoxian_ling",
    name: "招贤令",
    icon: "📜",
    rarity: "epic",
    setId: null,
    category: "resource",
    tags: ["skillCard", "resource"],
    effect: { description: "精英/Boss战后必定获得一张技能卡牌", scope: "team" },
    effectText: "精英/Boss战后必定获得一张技能卡牌",
    effects: { refundSkillCard: true },
    source: "elite",
    lore: "李世民设天策府，以'招贤榜'广纳天下英俊，秦琼、程咬金等皆由此入幕。",
  },

  // ═══════════════════════════════════════════════════════
  // 九、散件遗物 — 探索辅助（explore）
  // ═══════════════════════════════════════════════════════
  {
    id: "sinan",
    name: "司南",
    icon: "🧭",
    rarity: "common",
    setId: null,
    category: "explore",
    tags: ["reveal"],
    effect: { description: "显示下一层所有节点类型", scope: "global" },
    effectText: "显示下一层所有节点类型",
    effects: { revealNodes: true },
    source: "treasure",
    lore: "以磁石勺形置于铜地盘之上，勺柄指南。军中斥候以此辨别方向，避险就坦。",
  },
  {
    id: "map_scroll",
    name: "地图残卷",
    icon: "🗺️",
    rarity: "rare",
    setId: null,
    category: "explore",
    tags: ["guaranteedTreasure"],
    effect: { description: "下一层必定出现1个宝物节点", scope: "global" },
    effectText: "下一层必定出现1个宝物节点",
    effects: { guaranteedTreasure: true },
    source: "treasure",
    lore: "裴行俨随父征战时手绘的山川形势图，详注各处关隘与隐蔽路径，后散落军中为兵卒所得。",
  },
  {
    id: "xianren_zhi",
    name: "仙人指路",
    icon: "✨",
    rarity: "epic",
    setId: null,
    category: "explore",
    tags: ["treasureAfterElite"],
    effect: { description: "精英节点后必定连接一个宝物节点", scope: "global" },
    effectText: "精英节点后必定连接一个宝物节点",
    effects: { treasureAfterElite: true },
    source: "event",
    lore: "玄奘西行归来后口述见闻，由辨机和尚笔录成《大唐西域记》，详载各国山川险易，商旅皆视为至宝。",
  },
  {
    id: "tianyan_tong",
    name: "天眼通",
    icon: "👁️",
    rarity: "legendary",
    setId: null,
    category: "explore",
    tags: ["revealAll"],
    effect: { description: "永久显示所有未探索节点类型", scope: "global" },
    effectText: "永久显示所有未探索节点类型",
    effects: { revealAllNodes: true },
    source: "boss",
    lore: "李靖精研天文历算，能以星象占卜敌情远近。其推演之法秘不外传，后由弟子整理成《卫公兵法·天卷》。",
  },

  // ═══════════════════════════════════════════════════════
  // 十、散件遗物 — 特殊机制（special）
  // ═══════════════════════════════════════════════════════
  {
    id: "zhentianlei",
    name: "震天雷",
    icon: "💥",
    rarity: "epic",
    setId: null,
    category: "special",
    tags: ["bossDamage", "team"],
    effect: { description: "全队对Boss伤害+35%", scope: "team" },
    effectText: "全队对Boss伤害+35%",
    effects: { bossDamagePct: 0.35 },
    source: "elite",
    lore: "唐代火药武器，以铁罐盛之，临阵投掷，声震数里。李靖平突厥时曾用此物破敌营。",
  },
  {
    id: "xuezhan_qi",
    name: "血战旗",
    icon: "🚩",
    rarity: "epic",
    setId: null,
    category: "special",
    tags: ["damage", "team", "conditional"],
    effect: { description: "全队生命值>50%时，对所有目标伤害+20%", scope: "team" },
    effectText: "全队生命值>50%时，对所有目标伤害+20%",
    effects: { physicalDamagePct: 0.20, strategyDamagePct: 0.20 },
    source: "event",
    lore: "窦建德起义时高举的红色战旗，上书'义'字，激励全军死战不退。",
  },
  {
    id: "heshibi",
    name: "和氏璧",
    icon: "💎",
    rarity: "legendary",
    setId: null,
    category: "special",
    tags: ["controlImmune", "reflect", "team"],
    effect: { description: "全队免疫控制类debuff；首次受控时反击攻击者", scope: "team" },
    effectText: "全队免疫控制类debuff；首次受控时反击攻击者",
    effects: { controlImmune: true, controlReflect: true },
    source: "boss",
    lore: "春秋卞和献玉，秦以十五城易之。李渊入长安得此璧于宫中密室，后为传国玉玺之材。",
  },
  {
    id: "chuanguo_yuxi",
    name: "传国玉玺",
    icon: "🔴",
    rarity: "legendary",
    setId: null,
    category: "special",
    tags: ["victoryStack", "team"],
    effect: { description: "战斗胜利后，使下一场战斗全队攻击+15%（可叠加3层）", scope: "team" },
    effectText: "战斗胜利后，使下一场战斗全队攻击+15%（可叠加3层）",
    effects: { victoryStack: 0.15 },
    source: "boss",
    lore: "秦始皇以和氏璧制玉玺，书'受命于天，既寿永昌'。尉迟敬德玄武门之变后入宫取玺，李唐皇权由此正名。",
  },
  {
    id: "jiuzhuan_huanhun",
    name: "九转还魂香",
    icon: "🕯️",
    rarity: "epic",
    setId: null,
    category: "special",
    tags: ["nearDeathHeal", "team"],
    effect: { description: "任意武将濒死（HP<15%）时，恢复其25%最大兵力，每层1次", scope: "self" },
    effectText: "任意武将濒死（HP<15%）时，恢复其25%最大兵力，每层1次",
    effects: { nearDeathHealPct: 0.25 },
    source: "event",
    lore: "《旧唐书·方伎传》载名医张文仲有此回阳方。裴行俨曾于绝境中以此再生，后失传于世。",
  },
  {
    id: "jin_jia",
    name: "金甲",
    icon: "🛡️",
    rarity: "legendary",
    setId: null,
    category: "special",
    tags: ["lethalImmune", "team"],
    effect: { description: "全队免疫一次致命伤害，每层仅触发一次", scope: "team" },
    effectText: "全队免疫一次致命伤害，每层仅触发一次",
    effects: { lethalImmune: true },
    source: "boss",
    lore: "李世民洛阳之战中所穿贴金明光铠，万军之中护其周全。今藏于秦王府中，为镇国之器。",
  },
];

// 套装池（按套装ID分组）
export const SET_IDS = ["zhenguan", "kaiyuan", "dianmo", "wude"] as const;

// 宝物节点掉落配置（返回该稀有度的遗物池子）
export const TREASURE_DROP_RELICS = RELIC_POOL.filter(
  (r) => r.source === "treasure"
);
export const ELITE_DROP_RELICS = RELIC_POOL.filter(
  (r) => r.source === "elite" || r.source === "treasure"
);
export const BOSS_DROP_RELICS = RELIC_POOL.filter(
  (r) => r.source === "boss" || r.source === "elite"
);
