import type { Relic } from "./types";

export const RELIC_POOL: Relic[] = [
  // 稀有遗物 (Rare)
  {
    id: "kaihuanglvjian",
    name: "开皇律简",
    icon: "📜",
    rarity: "rare",
    history:
      "隋文帝时期颁布的《开皇律》竹简残卷，是隋唐法律制度的基础，规范朝纲、安定民心。",
    effectText: "全队防御+8%，受负面概率-5%，每回合结束恢复全队3%兵力。",
    effects: { defensePct: 0.08, debuffResistChance: 0.05, turnEndHealPct: 0.03 },
  },
  {
    id: "suidaibingfu",
    name: "隋代兵符",
    icon: "🛡️",
    rarity: "rare",
    history: "隋代调兵遣将兵符，象征古代军事权力。",
    effectText: "全队统御+10%，攻城+15%，物理伤害+8%。",
    effects: { commandPct: 0.1, siegePct: 0.15, physicalDamagePct: 0.08 },
  },
  {
    id: "lantingxumoben",
    name: "兰亭序摹本（隋唐版）",
    icon: "🖌️",
    rarity: "rare",
    history: "隋唐时期临摹《兰亭序》珍品，体现文化繁荣。",
    effectText: "全队谋略+12%，战法发动概率+5%，谋略伤害+6%。",
    effects: { strategyPct: 0.12, activeSkillChancePct: 0.05, strategyDamagePct: 0.06 },
  },
  {
    id: "dayunhecaoyin",
    name: "大运河漕印",
    icon: "🚢",
    rarity: "rare",
    history: "隋唐漕运管理官印，见证大运河贯通南北。",
    effectText: "全队攻城+12%，每回合获得资源，防御+8%。",
    effects: { siegePct: 0.12, resourcePerTurn: 18, defensePct: 0.08 },
  },
  {
    id: "tangsancaimayong",
    name: "唐三彩马俑",
    icon: "🐎",
    rarity: "rare",
    history: "隋唐代表性马俑工艺，见证时代繁荣与交流。",
    effectText: "全队骑兵速度+10%，物理伤害+7%，每回合6%概率骑兵连击一次。",
    effects: { cavalrySpeedPct: 0.1, physicalDamagePct: 0.07, cavalryDoubleStrikeChance: 0.06 },
  },
  {
    id: "fangkongqianfan",
    name: "隋代方孔钱范",
    icon: "🪙",
    rarity: "rare",
    history: "隋代五铢钱钱范，规范全国货币制度。",
    effectText: "全队统御+8%，资源产出效率+10%，受谋略伤害-6%。",
    effects: { commandPct: 0.08, resourceEfficiencyPct: 0.1, strategyDamageReductionPct: 0.06 },
  },
  {
    id: "yantabeitie",
    name: "雁塔碑帖",
    icon: "🗿",
    rarity: "rare",
    history: "隋唐碑帖文献，见证文化鼎盛。",
    effectText: "全队谋略+10%，战法发动概率+4%，谋略属性额外+7%。",
    effects: { strategyPct: 0.17, activeSkillChancePct: 0.04 },
  },
  {
    id: "suidaikaijiacanpian",
    name: "隋代铠甲残片",
    icon: "🧱",
    rarity: "rare",
    history: "隋代军用铠甲残片，体现军事装备水平。",
    effectText: "全队防御+11%，受物理伤害-7%，兵力低于60%额外防御+5%。",
    effects: {
      defensePct: 0.11,
      physicalDamageReductionPct: 0.07,
      lowTroopsDefenseBonusPct: 0.05,
      lowTroopsThreshold: 0.6,
    },
  },
  {
    id: "tangdaichajingchaoben",
    name: "唐代茶经抄本",
    icon: "🍵",
    rarity: "rare",
    history: "唐代《茶经》手抄本，见证茶文化兴起。",
    effectText: "全队谋略+9%，治疗效果+10%，每回合恢复全队4%兵力。",
    effects: { strategyPct: 0.09, healEffectPct: 0.1, turnEndHealPct: 0.04 },
  },
  {
    id: "suitangfenghuotailingpai",
    name: "隋唐烽火台令牌",
    icon: "🔥",
    rarity: "rare",
    history: "隋唐烽火台军情令牌，见证边防通讯体系。",
    effectText: "全队速度+8%，物理伤害+6%，强化侦查能力。",
    effects: { speedPct: 0.08, physicalDamagePct: 0.06 },
  },
  // 普通遗物 (Common)
  {
    id: "white_copper_tally",
    name: "铜节残符",
    icon: "🪙",
    rarity: "common",
    history: "旧军营遗落的铜节，虽不起眼，却能稳住军心。",
    effectText: "全队防御+2%。",
    effects: { defensePct: 0.02 },
  },
  {
    id: "white_oil_lamp",
    name: "行营油灯",
    icon: "🪔",
    rarity: "common",
    history: "夜行点灯，照路亦照心。",
    effectText: "全队速度+2%。",
    effects: { speedPct: 0.02 },
  },
  {
    id: "white_worn_sheath",
    name: "旧鞘",
    icon: "🗡️",
    rarity: "common",
    history: "磨损严重的刀鞘，仍能提醒武人守序。",
    effectText: "全队物理伤害+2%。",
    effects: { physicalDamagePct: 0.02 },
  },
  {
    id: "white_bamboo_abacus",
    name: "竹算筹",
    icon: "🧮",
    rarity: "common",
    history: "军需官常备小器，精打细算。",
    effectText: "每回合获得金币+6。",
    effects: { resourcePerTurn: 6 },
  },
  {
    id: "white_horse_bell",
    name: "驿马铃",
    icon: "🔔",
    rarity: "common",
    history: "驿卒铃响，队列更易齐步。",
    effectText: "骑兵速度+3%。",
    effects: { cavalrySpeedPct: 0.03 },
  },
  {
    id: "white_herb_bag",
    name: "草药囊",
    icon: "🌿",
    rarity: "common",
    history: "行军常备，聊胜于无。",
    effectText: "每回合结束恢复全队1%兵力。",
    effects: { turnEndHealPct: 0.01 },
  },
  {
    id: "white_small_banner",
    name: "小纛旗",
    icon: "🚩",
    rarity: "common",
    history: "伍长所持，鼓舞邻队。",
    effectText: "全队统率+2%。",
    effects: { commandPct: 0.02 },
  },
  {
    id: "white_old_manual",
    name: "旧操典",
    icon: "📘",
    rarity: "common",
    history: "残卷犹在，仍可习阵。",
    effectText: "全队攻城+3%。",
    effects: { siegePct: 0.03 },
  },
  // 稀有遗物 (Uncommon)
  {
    id: "green_war_drum",
    name: "行军战鼓",
    icon: "🥁",
    rarity: "uncommon",
    history: "鼓点稳阵，前后呼应。",
    effectText: "全队速度+4%，统率+3%。",
    effects: { speedPct: 0.04, commandPct: 0.03 },
  },
  {
    id: "green_quiver",
    name: "鹰羽箭囊",
    icon: "🏹",
    rarity: "uncommon",
    history: "精选箭羽，破甲更稳。",
    effectText: "全队物理伤害+4%。",
    effects: { physicalDamagePct: 0.04 },
  },
  {
    id: "green_tactic_slip",
    name: "战术简牍",
    icon: "📗",
    rarity: "uncommon",
    history: "简明战术，强调协同。",
    effectText: "全队谋略+5%。",
    effects: { strategyPct: 0.05 },
  },
  {
    id: "green_supply_cart",
    name: "补给车契",
    icon: "🛒",
    rarity: "uncommon",
    history: "登记军需，减少浪费。",
    effectText: "每回合获得金币+10，资源效率+4%。",
    effects: { resourcePerTurn: 10, resourceEfficiencyPct: 0.04 },
  },
  {
    id: "green_guard_plate",
    name: "护心铜片",
    icon: "🛡",
    rarity: "uncommon",
    history: "贴甲于胸，聊增生机。",
    effectText: "全队防御+5%，受物理伤害-2%。",
    effects: { defensePct: 0.05, physicalDamageReductionPct: 0.02 },
  },
  {
    id: "green_signal_fire",
    name: "烽火引",
    icon: "🔥",
    rarity: "uncommon",
    history: "边烽传令，军情更快。",
    effectText: "战法发动概率+2%。",
    effects: { activeSkillChancePct: 0.02 },
  },
  {
    id: "green_horse_hoof",
    name: "铁蹄钉",
    icon: "🐴",
    rarity: "uncommon",
    history: "稳蹄易行，利于追击。",
    effectText: "骑兵速度+6%，骑兵连击率+2%。",
    effects: { cavalrySpeedPct: 0.06, cavalryDoubleStrikeChance: 0.02 },
  },
  {
    id: "green_medical_scroll",
    name: "军医札记",
    icon: "📙",
    rarity: "uncommon",
    history: "营中急救要诀，重在止损。",
    effectText: "治疗效果+5%，每回合结束恢复全队2%兵力。",
    effects: { healEffectPct: 0.05, turnEndHealPct: 0.02 },
  },
];

// 遗物稀有度权重
export const RELIC_RARITY_WEIGHT: Record<Relic["rarity"], number> = {
  common: 50,
  uncommon: 30,
  rare: 15,
  legendary: 5,
};

// 敌方波次遗物配置
export const ENEMY_WAVE_RELIC_CONFIG: Record<number, string> = {
  3: "suidaibingfu",
  5: "kaihuanglvjian",
  8: "suitangfenghuotailingpai",
  12: "suidaikaijiacanpian",
};
